version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 8080:80
    depends_on:
      - postgres

  web:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:4000
    volumes:
      - .:/app